### ISSUE TITLE
Definición de Base de datos no relacional (NoSQL)

### ISSUE THREAD

**Issue by josejuansanchez** [gbd-asir-iescelia/glosario#15]

**Comment by manueljesus1995** [comment]
Creo haberlo echo bien ya te lo he mandado el Pull Request en caso de que no lo recibas te dejo mi correo manueljesus1995ns20@gmail.com, como ya te comente mañana no voy y me gustaría saber si lo he echo bien un saludo MJ

**Comment by josejuansanchez** [comment]
@manueljesus1995 No he recibido el PR, vuelve a enviarlo.

Para saber si lo has relizado correctamente puedes comprobar si aparece en la lista de *Pull Requests* del repositorio.

https://github.com/asir-iescelia/gbd-glosario-18-19/pulls

**Comment by manueljesus1995** [comment]
Buenas si me sale en repositorio y me pone que lo he realizado hace 2 horas
voy a probar a hacerlo de nuevo haber

**Comment by manueljesus1995** [comment]
En principio se supone que lo he realizado por que me aparece en Pull Request pero por lo que sea no sale lo he hecho de nuevo de todas formas ya me comentas si te sale, gracias y perdón por las molestias causadas.
