### ISSUE TITLE
Definición de Organización secuencial en archivos

### ISSUE THREAD

**Issue by josejuansanchez** [gbd-asir-iescelia/glosario#23]

**Comment by angeldmartinez** [comment]
Es una forma básica de organizar un conjunto de registros, los cuales forman un archivo utilizando una organización secuencial. En este los archivos quedan organizados consecutivamente, por norma general los archivos quedan grabados según el valor que se le aporte a cada campo de registro. La forma mas común del archivo es el archivo secuencial.
