### ISSUE TITLE
Definición de Organización secuencial encadenada en archivos

### ISSUE THREAD

**Issue by josejuansanchez** [gbd-asir-iescelia/glosario#24]

**Comment by angeldmartinez** [comment]
Es un tipo de organización, que cada registro se almacena un puntero con una direccion logica. Estos ficheros solo pueden ser gestionados en soportes direccionales. Ademas pueden realizar otras operaciones como: Inserción, Recuperacion o consulta de datos, Borrado, Modificacion, Carracteristicas(las cuales se organiza la cadena)
